name: publish to nuget
on:
  push:
    branches:
      - master # Default release branch
jobs:
  pack-push:
    env:
      PROJECT_PATH: ./Braspag.Authentication/Braspag.Authentication.nuspec

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101

    - name: Geração do package
      run: nuget pack ${{ env.PROJECT_PATH }} -IncludeReferencedProjects

    - name: Push no NuGet
      run: |
        cd out
        dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ secrets.NUGET_SERVER }} --skip-duplicate
